name: hapiserver
base: core18
version: '1.0.11'
summary: Generic HAPI Server for x64 Linux
description: |
  Generic HAPI Server for x64 Linux
grade: devel
confinement: devmode
architectures:
  - build-on: amd64

apps:
  curl:
    command: curl
  hapiserver-test:
     command: /snap/hapiserver/current/hapi-server-v1.0.11/bin/node /snap/hapiserver/current/hapi-server-v1.0.11/test/server-test.js --logdir="/tmp/log" --metadir="/tmp/meta"
  hapiserver:
    command: /snap/hapiserver/current/hapi-server-v1.0.11/hapi-server --logdir="/tmp/log" --metadir="/tmp/meta" 

parts:
  curl:
    source: http://curl.haxx.se/download/curl-7.45.0.tar.bz2
    plugin: autotools
  hapiserver-test:
    source: https://github.com/KSR4599/hapi-server-snap/releases/download/v1.0.11/hapi-server-v1.0.11.tgz
    plugin: dump
  hapiserver:
    source: https://github.com/KSR4599/hapi-server-snap/releases/download/v1.0.11/hapi-server-v1.0.11.tgz
    plugin: dump
